name: 'Connect Studies and Resources'
description: 'Looks through portal files metadata to find mentions of resources in the Resource table (currently limited to Cell Line and Animal Model resources) and creates a table with studyId + resourceId/core subset of resource info columns.'
inputs:
  files:
    description: 'Portal files table syn ID'
    required: true
  resources:
    description: 'Resource table syn ID'
    required: true
  result:
    description: 'Result table syn ID'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.files }}
    - ${{ inputs.resources }}
    - ${{ inputs.result }}
