name: 'Schematic auth'
description: 'Helps set up schematic auth for Synapse and Google services'
inputs:
  authtoken:
    description: 'Synapse authtoken'
    required: true
  servicekey: # service_account_key in https://github.com/google-github-actions/setup-gcloud/blob/master/action.yml
    description: 'Google API service key that should have scope for GoogleSheets'
    required: true
runs:
  using: "composite"
  steps:
    - run: ${{ github.action_path }}/schematic_auth.sh -a ${{ inputs.authtoken }} -s ${{ inputs.servicekey }}
      shell: bash

