name: Scheduled rebuild STUDY_RESOURCE

on:
  schedule:
    # Runs at 3:11 AM (PST) on day 3,17 of month
    - cron:  '11 11 3,17 * *'
    
  # Also can run manually from the Actions tab
  workflow_dispatch:
  

jobs:
  build:
    name: Rebuild STUDY_RESOURCE
    runs-on: ubuntu-latest
    steps:
      - uses: nf-osi/actions/connect-study-resource@e54ae366ae312229fbab989da0ebf5de532f7ef8
        with: 
          files: syn16858331
          resources: syn26450069
          result: syn26461958 # pass this to version job as well
          project: syn26451327
        env: 
          SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
          
  version:
    name: Synapse versioning of new build
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: nf-osi/actions/create-table-snapshot@451d4e143ab09c98d5b9c900200bc2978e7bc378
        with: 
          table: syn26461958
        env: 
          SYNAPSE_AUTH_TOKEN: ${{ secrets.SYNAPSE_AUTH_TOKEN }}
