# This works for setup of schematic for versions of schematic >= v23.1.1
# It furnishes a generic config.yml file -- most usage does require `-c config.yml`
# Whether setup should also include authentication and service keys depends on the intended usage:
# Commands such as `schema convert` and `model validate` don't require authentication, while commands such as `manifest get` do. 

name: Setup schematic
description: Setup a specific version of schematic from GitHub source
author: Anh Nguyet Vu

inputs:
  schematic-version:
    description: The tag or commit sha to use.
    default: v23.1.1
  data-model:
    description: "The data model to use in the current workspace (written into the config), e.g. './DM.jsonld'"
    required: false
    default: ''
  auth-token:
    description: 'Synapse authentication token, only needed for some functions of schematic'
    required: false
    default: ''
  service-key: # same as service_account_key in https://github.com/google-github-actions/setup-gcloud/blob/master/action.yml
    description: 'Google API service key with scope for GoogleSheets, only needed for some functions of schematic'
    required: false
    default: ''

runs:
  using: "composite"
  steps:

    # Check out schematic into a side repo called schematic...
    - name: Check out schematic
      uses: actions/checkout@v3
      with:
        repository: Sage-Bionetworks/schematic
        path: schematic
        fetch-depth: 0

    # Switch to indicated version
    - run: git checkout ${{ inputs.schematic-version }}
      working-directory: schematic
      shell: bash
    
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install schematic version
      working-directory: schematic
      run: pip3 install schematicpy
      shell: bash

    # Write data model into config
    - name: Update model in config
      shell: bash
      run: sed "s/SCHEMA_JSONLD_LOCATION/${{ inputs.data-model }}/" $GITHUB_ACTION_PATH/config.yml > $GITHUB_WORKSPACE/config.yml

    #----------------------------------------------
    #     Set up auth-related files if needed
    #----------------------------------------------

    # This should be passed in as a SECRETS variable
    - name: Furnish Synapse config
      shell: bash
      run: printf "[authenthication]\nauthtoken = ${{ inputs.auth-token }}" > $GITHUB_WORKSPACE/.synapseConfig

    # This should be passed in as a SECRETS variable
    - name: Furnish service token
      shell: bash
      run: echo ${{ inputs.service-key }} > $GITHUB_WORKSPACE/schematic_service_account_creds.json
    
    
 
  
