name: Setup schematic
description: Setup a specific version of schematic from GitHub source
author: Anh Nguyet Vu

inputs:
  schematic-version:
    description: The tag or commit sha to use.
    default: v21.06
  auth-token:
    description: 'Synapse authentication token, only provide if needed for some functions of schematic'
    required: false
    default: ''
  service-key: # same as service_account_key in https://github.com/google-github-actions/setup-gcloud/blob/master/action.yml
    description: 'Google API service key with scope for GoogleSheets, only provide if needed for some functions of schematic'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - name: Check out schematic
      uses: actions/checkout@v3
      with:
        repository: Sage-Bionetworks/schematic
        path: schematic
        fetch-depth: 0

    - run: git checkout ${{ inputs.schematic-version }}
      working-directory: schematic
      shell: bash

    - name: Install Poetry
      run: pipx install poetry
      shell: bash
    
    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'
        cache: 'poetry'
        cache-dependency-path: '**/poetry.lock'
    
    - name: Install and activate schematic version
      working-directory: schematic
      run: |
        poetry install --no-interaction
        echo "SCHEMATIC_ENV=$(poetry env info --path)/bin/activate" >> $GITHUB_ENV
      shell: bash

    # Issues with configs not being backwards-compatible so might need to handle this better
    - run: mv $GITHUB_ACTION_PATH/config.yml $GITHUB_WORKSPACE/config.yml
      shell: bash

    #----------------------------------------------
    #     setup auth-related files if needed
    #----------------------------------------------
    - name: Furnish config and auth files
      run: $GITHUB_ACTION_PATH/setup_schematic_auth.sh ${{ inputs.auth-token }} ${{ inputs.service-key }}
      shell: bash
    
 
  
