name: Setup schematic
description: Setup a specific version of schematic from GitHub source
author: Anh Nguyet Vu

inputs:
  schematic-version:
    description: The tag or commit sha to use.
    default: v21.06
  auth-token:
    description: 'Synapse authentication token, only provide if needed for some functions of schematic'
    required: false
    default: ''
  service-key: # same as service_account_key in https://github.com/google-github-actions/setup-gcloud/blob/master/action.yml
    description: 'Google API service key with scope for GoogleSheets, only provide if needed for some functions of schematic'
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    #----------------------------------------------
    #      set-up python
    #----------------------------------------------
    - name: Set up python
      id: setup-python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    #----------------------------------------------
    #      install & configure poetry  
    #----------------------------------------------
    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: false
        installer-parallel: true
    
    #----------------------------------------------
    #     install schematic
    #----------------------------------------------
    - name: Check out schematic
      id: checkout-schematic
      uses: actions/checkout@v3
      with:
        repository: Sage-Bionetworks/schematic
        path: schematic
        fetch-depth: 0
    
    - run: git checkout ${{ inputs.schematic-version }}
      shell: bash
    
    - name: Install schematic
      working-directory: schematic
      run: poetry install --no-interaction
      shell: bash
      
    - name: Activate
      run: source .venv/bin/activate
      shell: bash

    # Issues with configs not being backwards-compatible so might need to handle this better
    - run: mv $GITHUB_ACTION_PATH/config.yml $GITHUB_WORKSPACE/config.yml
      shell: bash

    #----------------------------------------------
    #     setup auth-related files if needed
    #----------------------------------------------
    - name: Furnish config and auth files
      run: $GITHUB_ACTION_PATH/setup_schematic_auth.sh ${{ inputs.auth-token }} ${{ inputs.service-key }}
      shell: bash
    
 
  
