name: 'Get manifest template(s)'
description: 'Use schematic to generate specified manifest template(s)'
inputs:
  templates:
    description: 'One or more templates as comma-delimited string'
    required: true
  jsonld:
    description: 'Schema jsonld file location'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '-t'
    - ${{ inputs.templates }}
    - '-j'
    - ${{ inputs.jsonld }}
